name: "Documentation Maintenance"
description: "Automatically maintain and update documentation when infrastructure changes occur"
version: "1.0.0"

triggers:
  - type: "file_change"
    patterns:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
      - "terraform/modules/*/README.md"
      - "README*.md"
    exclude_patterns:
      - "terraform/**/.terraform/**"
      - "terraform/**/terraform.tfstate*"
      - "**/.git/**"

  - type: "manual"
    description: "Manual trigger for comprehensive documentation review"

actions:
  - name: "validate_terraform_documentation"
    description: "Ensure all Terraform modules have proper documentation"
    steps:
      - check_module_readme_exists
      - validate_variable_documentation
      - verify_output_documentation
      - check_example_usage

  - name: "update_infrastructure_diagrams"
    description: "Update architecture diagrams when infrastructure changes"
    steps:
      - analyze_terraform_changes
      - identify_architecture_impacts
      - suggest_diagram_updates
      - validate_diagram_consistency

  - name: "maintain_workflow_documentation"
    description: "Keep workflow documentation synchronized with actual implementations"
    steps:
      - analyze_github_workflow_changes
      - update_deployment_procedures
      - verify_command_accuracy
      - check_environment_consistency

  - name: "validate_documentation_links"
    description: "Ensure all documentation links are valid and current"
    steps:
      - scan_markdown_files
      - validate_internal_links
      - check_external_references
      - report_broken_links

  - name: "check_documentation_completeness"
    description: "Identify gaps in documentation coverage"
    steps:
      - analyze_code_coverage
      - identify_undocumented_features
      - check_troubleshooting_completeness
      - suggest_documentation_improvements

configuration:
  validation_rules:
    terraform_modules:
      require_readme: true
      require_variable_descriptions: true
      require_output_descriptions: true
      require_usage_examples: true
      
    markdown_standards:
      max_line_length: 120
      require_headers: true
      require_table_of_contents: false
      check_spelling: true
      
    link_validation:
      check_internal_links: true
      check_external_links: true
      timeout_seconds: 30
      retry_attempts: 3

  notification_settings:
    slack_webhook: "${SLACK_WEBHOOK_URL}"
    email_recipients:
      - "platform-team@company.com"
    
  reporting:
    generate_summary: true
    include_metrics: true
    save_to_file: ".kiro/reports/documentation-maintenance.md"

safety_controls:
  max_files_processed: 100
  max_execution_time_minutes: 30
  require_approval_for:
    - major_documentation_restructuring
    - external_link_modifications
    - workflow_procedure_changes

escalation:
  conditions:
    - documentation_coverage_below_80_percent
    - broken_links_exceed_10
    - terraform_modules_without_documentation
    - workflow_documentation_inconsistencies
  
  actions:
    - notify_platform_team
    - create_github_issue
    - schedule_documentation_review

metrics:
  track:
    - documentation_coverage_percentage
    - broken_links_count
    - outdated_documentation_items
    - documentation_update_frequency
    - validation_success_rate
  
  targets:
    - documentation_coverage: ">= 90%"
    - broken_links: "< 5"
    - outdated_items: "< 10"
    - update_frequency: ">= weekly"