name: "Security Compliance and Configuration Review"
description: "Automated security configuration review, IAM policy auditing, network security validation, and access pattern analysis"
version: "1.0.0"

trigger:
  type: "scheduled"
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  
  manual_trigger: true
  
  events:
    - "iam_policy_change"
    - "security_group_modification"
    - "network_policy_update"
    - "secret_access_anomaly"
    - "compliance_violation_detected"

configuration:
  compliance_frameworks:
    - "CIS_Kubernetes_Benchmark"
    - "AWS_Security_Best_Practices"
    - "NIST_Cybersecurity_Framework"
    - "SOC2_Type_II"
    
  security_domains:
    - "identity_and_access_management"
    - "network_security"
    - "data_protection"
    - "logging_and_monitoring"
    - "incident_response"
    - "vulnerability_management"
  
  audit_scope:
    aws_services:
      - "iam"
      - "ec2"
      - "eks"
      - "s3"
      - "kms"
      - "cloudtrail"
      - "vpc"
    
    kubernetes_resources:
      - "rbac"
      - "network_policies"
      - "pod_security_policies"
      - "secrets"
      - "service_accounts"
      - "admission_controllers"

actions:
  - name: "iam_policy_audit"
    description: "Comprehensive IAM policy analysis and compliance check"
    commands:
      - "aws iam list-roles --query 'Roles[?contains(RoleName, `eks-learning-lab`)]'"
      - "aws iam list-policies --scope Local --query 'Policies[?contains(PolicyName, `eks-learning-lab`)]'"
      - "aws iam get-account-authorization-details --filter Role,Policy"
    
    validations:
      - name: "least_privilege_principle"
        rule: "IAM policies should follow least privilege principle"
        checks:
          - "no_wildcard_actions_in_production"
          - "no_admin_access_without_mfa"
          - "resource_specific_permissions"
          - "time_based_access_controls"
      
      - name: "role_trust_relationships"
        rule: "IAM role trust relationships should be restrictive"
        checks:
          - "no_wildcard_principals"
          - "external_id_required_for_cross_account"
          - "condition_keys_properly_used"
      
      - name: "unused_permissions_detection"
        rule: "Identify and flag unused IAM permissions"
        analysis: "access_analyzer_findings"
    
  - name: "network_security_validation"
    description: "Network security configuration and policy validation"
    commands:
      - "aws ec2 describe-security-groups --filters Name=group-name,Values=*eks-learning-lab*"
      - "aws ec2 describe-network-acls --filters Name=tag:Project,Values=eks-learning-lab"
      - "kubectl get networkpolicies -A"
      - "kubectl get pods -A -o jsonpath='{.items[*].spec.securityContext}'"
    
    validations:
      - name: "security_group_rules"
        rule: "Security groups should follow restrictive access patterns"
        checks:
          - "no_unrestricted_inbound_access"
          - "minimal_port_exposure"
          - "source_ip_restrictions"
          - "protocol_specific_rules"
      
      - name: "network_policies_enforcement"
        rule: "Network policies should be defined for all namespaces"
        checks:
          - "default_deny_policy_exists"
          - "ingress_rules_defined"
          - "egress_rules_defined"
          - "cross_namespace_communication_controlled"
      
      - name: "pod_security_standards"
        rule: "Pods should adhere to security standards"
        checks:
          - "non_root_user_enforcement"
          - "read_only_root_filesystem"
          - "no_privileged_containers"
          - "security_context_defined"
    
  - name: "encryption_settings_verification"
    description: "Verify encryption at rest and in transit configurations"
    commands:
      - "aws kms list-keys --query 'Keys[*].KeyId'"
      - "aws s3api get-bucket-encryption --bucket eks-learning-lab-dev-lgtm-prometheus"
      - "aws eks describe-cluster --name eks-learning-lab-dev-cluster --query 'cluster.encryptionConfig'"
      - "kubectl get secrets -A -o jsonpath='{.items[*].type}'"
    
    validations:
      - name: "kms_encryption_enabled"
        rule: "All sensitive data should be encrypted with KMS"
        checks:
          - "eks_secrets_encryption_enabled"
          - "s3_bucket_encryption_enabled"
          - "ebs_volume_encryption_enabled"
          - "rds_encryption_enabled"
      
      - name: "tls_configuration"
        rule: "All communications should use TLS"
        checks:
          - "ingress_tls_termination"
          - "service_mesh_mtls_enabled"
          - "database_ssl_required"
          - "api_server_tls_configured"
    
  - name: "access_pattern_analysis"
    description: "Analyze access patterns and detect anomalies"
    commands:
      - "aws logs filter-log-events --log-group-name /aws/eks/eks-learning-lab-dev-cluster/cluster"
      - "kubectl get events -A --sort-by='.lastTimestamp' | grep -i 'auth\\|permission\\|access'"
      - "aws cloudtrail lookup-events --lookup-attributes AttributeKey=EventName,AttributeValue=AssumeRole"
    
    analysis:
      - name: "unusual_access_patterns"
        detection:
          - "off_hours_access"
          - "geographic_anomalies"
          - "privilege_escalation_attempts"
          - "failed_authentication_spikes"
      
      - name: "service_account_usage"
        monitoring:
          - "unused_service_accounts"
          - "over_privileged_service_accounts"
          - "cross_namespace_access_patterns"
          - "external_system_access"
    
  - name: "vulnerability_assessment"
    description: "Container and infrastructure vulnerability scanning"
    commands:
      - "kubectl get pods -A -o jsonpath='{.items[*].spec.containers[*].image}' | tr ' ' '\\n' | sort -u"
      - "aws ecr describe-image-scan-findings --repository-name user-service"
    
    scans:
      - name: "container_image_vulnerabilities"
        tools: ["trivy", "clair", "aws_ecr_scanning"]
        severity_threshold: "HIGH"
      
      - name: "kubernetes_configuration_scan"
        tools: ["kube-bench", "kube-hunter", "polaris"]
        compliance_check: "CIS_Kubernetes_Benchmark"
      
      - name: "infrastructure_vulnerabilities"
        tools: ["aws_inspector", "aws_config"]
        scope: ["ec2_instances", "security_groups", "iam_policies"]

compliance_checks:
  cis_kubernetes:
    - name: "1.1.1_api_server_anonymous_auth"
      rule: "Ensure that the --anonymous-auth argument is set to false"
      command: "kubectl get pod -n kube-system -l component=kube-apiserver -o yaml | grep anonymous-auth"
      expected: "false"
    
    - name: "1.2.1_api_server_profiling"
      rule: "Ensure that the --profiling argument is set to false"
      command: "kubectl get pod -n kube-system -l component=kube-apiserver -o yaml | grep profiling"
      expected: "false"
    
    - name: "2.1_etcd_cert_file"
      rule: "Ensure that the --cert-file and --key-file arguments are set as appropriate"
      command: "kubectl get pod -n kube-system -l component=etcd -o yaml | grep -E 'cert-file|key-file'"
      validation: "both_present"
  
  aws_security:
    - name: "cloudtrail_enabled"
      rule: "Ensure CloudTrail is enabled in all regions"
      command: "aws cloudtrail describe-trails --query 'trailList[?IsMultiRegionTrail==`true`]'"
      validation: "at_least_one_trail"
    
    - name: "s3_bucket_public_access"
      rule: "Ensure S3 buckets are not publicly accessible"
      command: "aws s3api get-public-access-block --bucket eks-learning-lab-dev-lgtm-prometheus"
      validation: "all_public_access_blocked"
    
    - name: "vpc_flow_logs"
      rule: "Ensure VPC Flow Logs are enabled"
      command: "aws ec2 describe-flow-logs --filter Name=resource-type,Values=VPC"
      validation: "flow_logs_enabled"

security_policies:
  pod_security_standards:
    - name: "restricted_security_context"
      policy: |
        apiVersion: v1
        kind: Pod
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 2000
          containers:
          - securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
  
  network_policies:
    - name: "default_deny_all"
      policy: |
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: default-deny-all
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress
  
  opa_gatekeeper_constraints:
    - name: "required_labels"
      template: "k8srequiredlabels"
      constraint: |
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: K8sRequiredLabels
        metadata:
          name: must-have-environment
        spec:
          match:
            kinds:
            - apiGroups: ["apps"]
              kinds: ["Deployment"]
          parameters:
            labels: ["environment", "app", "version"]

incident_response:
  security_events:
    - name: "unauthorized_access_attempt"
      severity: "high"
      triggers:
        - "multiple_failed_authentications"
        - "privilege_escalation_detected"
        - "suspicious_network_activity"
      
      response_actions:
        - "isolate_affected_resources"
        - "collect_forensic_evidence"
        - "notify_security_team"
        - "initiate_incident_response_plan"
    
    - name: "data_exfiltration_detected"
      severity: "critical"
      triggers:
        - "unusual_data_transfer_patterns"
        - "unauthorized_s3_access"
        - "suspicious_api_calls"
      
      response_actions:
        - "block_suspicious_traffic"
        - "revoke_compromised_credentials"
        - "enable_enhanced_monitoring"
        - "escalate_to_management"

monitoring_and_alerting:
  security_metrics:
    - "failed_authentication_rate"
    - "privilege_escalation_attempts"
    - "network_policy_violations"
    - "unauthorized_api_calls"
    - "suspicious_file_access"
  
  alert_thresholds:
    - metric: "failed_authentication_rate"
      threshold: "> 10 per minute"
      severity: "warning"
    
    - metric: "privilege_escalation_attempts"
      threshold: "> 1 per hour"
      severity: "critical"
    
    - metric: "network_policy_violations"
      threshold: "> 5 per hour"
      severity: "warning"

reporting:
  compliance_report:
    format: "json"
    frequency: "daily"
    retention_days: 90
    
    sections:
      - "executive_summary"
      - "compliance_status"
      - "security_findings"
      - "risk_assessment"
      - "remediation_recommendations"
      - "trend_analysis"
  
  security_dashboard:
    enabled: true
    grafana_integration: true
    real_time_updates: true
    
    panels:
      - "security_score_overview"
      - "compliance_status"
      - "vulnerability_trends"
      - "access_pattern_analysis"
      - "incident_response_metrics"

integration:
  aws_security_hub:
    enabled: true
    finding_format: "ASFF"
    
  prometheus:
    enabled: true
    custom_metrics: true
    alert_manager_integration: true
  
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channel: "#security-alerts"
    
  jira:
    enabled: false
    project_key: "SEC"
    issue_type: "Security Finding"

remediation:
  automated_fixes:
    - name: "remove_unused_security_groups"
      condition: "security_group_unused_for_30_days"
      action: "delete_security_group"
      approval_required: true
    
    - name: "rotate_expired_certificates"
      condition: "certificate_expires_in_7_days"
      action: "request_new_certificate"
      approval_required: false
    
    - name: "update_vulnerable_images"
      condition: "high_severity_vulnerability_detected"
      action: "create_pull_request_with_updated_image"
      approval_required: true
  
  manual_remediation_guides:
    - finding: "overprivileged_iam_role"
      guide: "Review IAM role permissions and remove unnecessary privileges"
      documentation: "https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"
    
    - finding: "insecure_network_policy"
      guide: "Update network policy to restrict unnecessary traffic"
      documentation: "https://kubernetes.io/docs/concepts/services-networking/network-policies/"

audit_trail:
  enabled: true
  log_all_security_events: true
  retention_period: "7_years"
  
  logged_events:
    - "policy_changes"
    - "access_grants_revocations"
    - "security_configuration_changes"
    - "compliance_check_results"
    - "incident_response_actions"