name: "Supervised Mode Operations"
description: "Automated workflows for supervised infrastructure changes with human approval gates"
version: "1.0.0"

triggers:
  - type: "manual"
    name: "infrastructure_change_request"
    description: "Initiate supervised infrastructure change workflow"
    
  - type: "file_change"
    name: "terraform_change_detection"
    patterns: 
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
    description: "Detect Terraform configuration changes requiring approval"
    
  - type: "scheduled"
    name: "scaling_recommendation_analysis"
    schedule: "0 */6 * * *"  # Every 6 hours
    description: "Analyze resource utilization and generate scaling recommendations"

actions:
  infrastructure_change_workflow:
    description: "Complete supervised infrastructure change workflow"
    steps:
      - name: "analyze_change_request"
        action: "analyze_terraform_changes"
        parameters:
          include_impact_analysis: true
          generate_risk_assessment: true
          create_rollback_plan: true
          
      - name: "generate_change_summary"
        action: "create_human_readable_summary"
        parameters:
          include_cost_impact: true
          include_downtime_estimate: true
          include_affected_services: true
          
      - name: "request_approvals"
        action: "initiate_approval_workflow"
        parameters:
          approval_type: "based_on_risk_level"
          required_approvers: "auto_determine"
          timeout_hours: 24
          
      - name: "execute_with_monitoring"
        action: "supervised_terraform_apply"
        parameters:
          enable_real_time_monitoring: true
          auto_rollback_on_failure: true
          generate_execution_report: true

  scaling_recommendation_workflow:
    description: "Generate and present resource scaling recommendations"
    steps:
      - name: "collect_utilization_metrics"
        action: "analyze_resource_utilization"
        parameters:
          time_range: "7d"
          include_cost_metrics: true
          include_performance_metrics: true
          
      - name: "generate_recommendations"
        action: "create_scaling_recommendations"
        parameters:
          include_cost_benefit_analysis: true
          include_risk_assessment: true
          include_implementation_plan: true
          
      - name: "present_for_approval"
        action: "create_approval_request"
        parameters:
          include_data_visualization: true
          include_projected_outcomes: true
          required_approver: "technical_lead"

  change_impact_analysis:
    description: "Comprehensive impact analysis for infrastructure changes"
    steps:
      - name: "analyze_dependencies"
        action: "map_resource_dependencies"
        parameters:
          include_cross_workflow_impact: true
          include_service_dependencies: true
          include_data_dependencies: true
          
      - name: "assess_blast_radius"
        action: "calculate_change_impact"
        parameters:
          include_availability_impact: true
          include_performance_impact: true
          include_security_impact: true
          include_cost_impact: true
          
      - name: "generate_mitigation_strategies"
        action: "create_risk_mitigation_plan"
        parameters:
          include_rollback_procedures: true
          include_monitoring_plan: true
          include_communication_plan: true

parameters:
  risk_thresholds:
    low_risk:
      max_affected_services: 1
      max_downtime_minutes: 5
      max_cost_increase_percent: 10
      
    medium_risk:
      max_affected_services: 3
      max_downtime_minutes: 30
      max_cost_increase_percent: 25
      
    high_risk:
      max_affected_services: 5
      max_downtime_minutes: 120
      max_cost_increase_percent: 50

  approval_requirements:
    low_risk:
      required_approvers: ["senior_engineer"]
      approval_timeout_hours: 4
      
    medium_risk:
      required_approvers: ["tech_lead", "product_owner"]
      approval_timeout_hours: 12
      
    high_risk:
      required_approvers: ["architect", "engineering_manager", "security_lead"]
      approval_timeout_hours: 24

  scaling_thresholds:
    scale_up_triggers:
      cpu_utilization_percent: 70
      memory_utilization_percent: 80
      response_time_multiplier: 2.0
      error_rate_percent: 5
      
    scale_down_triggers:
      cpu_utilization_percent: 30
      memory_utilization_percent: 40
      request_rate_percent: 50
      duration_minutes: 60

  safety_limits:
    max_concurrent_changes: 2
    max_changes_per_day: 5
    min_time_between_changes_minutes: 30
    max_cost_increase_per_change_percent: 50
    max_instance_count_per_service: 20
    max_storage_size_gb: 1000

notifications:
  change_request_created:
    channels: ["slack", "email"]
    recipients: ["platform_team", "on_call_engineer"]
    
  approval_required:
    channels: ["slack", "email"]
    recipients: ["approvers", "change_requester"]
    
  change_executed:
    channels: ["slack", "email"]
    recipients: ["platform_team", "stakeholders"]
    
  change_failed:
    channels: ["slack", "email", "pagerduty"]
    recipients: ["platform_team", "on_call_engineer", "engineering_manager"]

integrations:
  terraform:
    enable_plan_analysis: true
    enable_state_validation: true
    enable_cost_estimation: true
    
  kubernetes:
    enable_resource_monitoring: true
    enable_health_checks: true
    enable_capacity_analysis: true
    
  aws:
    enable_cost_tracking: true
    enable_service_limit_monitoring: true
    enable_security_analysis: true
    
  monitoring:
    prometheus_endpoint: "http://prometheus-server.observability.svc.cluster.local"
    grafana_endpoint: "http://grafana.observability.svc.cluster.local"
    enable_custom_metrics: true

audit:
  log_all_actions: true
  retain_logs_days: 365
  include_approval_chain: true
  include_execution_details: true
  compliance_reporting: true