apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt staging server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: admin@k8s-demo.local
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: alb  # Will be overridden by ingress-specific settings
    # Also support DNS-01 challenge for Route53
    - dns01:
        route53:
          region: us-east-1
          # The AWS credentials will be provided via IRSA
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Let's Encrypt production server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration  
    email: admin@k8s-demo.local
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: alb
    # Also support DNS-01 challenge for Route53
    - dns01:
        route53:
          region: us-east-1